version: '3'
services:
  db:
    image: mysql:latest
    container_name: rouyi-vue-mysql
    ports:
      - "3306:3306"
    environment:
      # You can use whatever password you like
      - MYSQL_PASSWORD=password
      # Password for root access
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=ry-vue
    volumes:
      - /home/cuongnn/Documents/github/RuoYi-Vue/data/mysql/db:/var/lib/mysql
  cache:
    image: redis:6.2-alpine
    container_name: rouyi-vue-redis
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes:
      - /home/cuongnn/Documents/github/RuoYi-Vue/data/redis:/data