# Configuration of data sources
spring:
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driverClassName: com.mysql.cj.jdbc.Driver
        druid:
            # The main database source
            master:
                url: jdbc:mysql://localhost:3306/ry-vue?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
                username: root
                password: password
            # from the database source.
            slave:
                # Connect from the data source./default closed.
                enabled: false
                url: 
                username: 
                password: 
            # The initial number of connections
            initialSize: 5
            # Minimum number of connections.
            minIdle: 10
            # Maximum number of connections.
            maxActive: 20
            # Configuration to get connected waiting overtime time
            maxWait: 60000
            # Connect over time.
            connectTimeout: 30000
            # Network overtime.
            socketTimeout: 60000
            # How long is the interval for one testing?，Detection of free connections that need to be closed，The unit is millisecond.
            timeBetweenEvictionRunsMillis: 60000
            # Configure a connection for the minimum survival time in the pool，The unit is millisecond.
            minEvictableIdleTimeMillis: 300000
            # Configure a connection for the maximum survival time in the pool，The unit is millisecond.
            maxEvictableIdleTimeMillis: 900000
            # Configuration to verify whether the connection is effective
            validationQuery: SELECT 1 FROM DUAL
            testWhileIdle: true
            testOnBorrow: false
            testOnReturn: false
            webStatFilter: 
                enabled: true
            statViewServlet:
                enabled: true
                # Set a white list.，Not filling permits all access.
                allow:
                url-pattern: /druid/*
                # Console Management User Name and Password
                login-username: ruoyi
                login-password: 123456
            filter:
                stat:
                    enabled: true
                    # slowlySQLRecorded
                    log-slow-sql: true
                    slow-sql-millis: 1000
                    merge-sql: true
                wall:
                    config:
                        multi-statement-allow: true