# Projects related configuration
ruoyi:
  # The name
  name: RuoYi
  # The version
  version: 3.8.7
  # Copyright Year
  copyrightYear: 2024
  # The Document Route Examples（ WindowsConfigurationD:/ruoyi/uploadPath，LinuxConfiguration /home/ruoyi/uploadPath）
  profile: /home/cuongnn/Documents/github/RuoYi-Vue/data/uploadPath
  # obtainedipAddress is open.
  addressEnabled: false
  # Type of verification code math The numerical calculation char Verification of characters
  captchaType: math

# Development of environmental configuration
server:
  # The server.HTTPThe port.，I think8080
  port: 8080
  servlet:
    # Application Access Route
    context-path: /
  tomcat:
    # tomcatofURIcoded
    uri-encoding: UTF-8
    # Completed number of connections.，I think100
    accept-count: 1000
    threads:
      # tomcatThe maximum number of lines，I think200
      max: 800
      # TomcatStart the initial line number.，The default value10
      min-spare: 100

# Diary configuration.
logging:
  level:
    com.ruoyi: debug
    org.springframework: warn

# User Configuration
user:
  password:
    # The maximum number of errors.
    maxRetryCount: 5
    # Lock the time.（presumed10Minutes）
    lockTime: 10

# SpringConfiguration
spring:
  # Resource Information
  messages:
    # The International Resource Document Route
    basename: i18n/messages
  profiles:
    active: druid
  # The document is uploaded
  servlet:
    multipart:
      # The size of individual documents.
      max-file-size: 10MB
      # Set the total file size uploaded.
      max-request-size: 20MB
  # The Service Module
  devtools:
    restart:
      # Heat deployment switch
      enabled: true
  # redis Configuration
  redis:
    # Addressed
    host: localhost
    # The port.，I think6379
    port: 6379
    # The Database Index
    database: 0
    # The code
    password: eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    # Connect overtime.
    timeout: 10s
    lettuce:
      pool:
        # The smallest free connection in the pool.
        min-idle: 0
        # The largest free connection in the pool.
        max-idle: 8
        # The maximum number of database connections.
        max-active: 8
        # #Maximum blocking waiting time.（Use of negative values indicates no limitation）
        max-wait: -1ms

# tokenConfiguration
token:
  # Personalized identification.
  header: Authorization
  # The key.
  secret: abcdefghijklmnopqrstuvwxyz
  # Signs are valid.（presumed30Minutes）
  expireTime: 30

# MyBatisConfiguration
mybatis:
  # Search for specified package names
  typeAliasesPackage: com.ruoyi.**.domain
  # ConfigurationmapperThe scanning.，Find all.mapper.xmlShowing documents
  mapperLocations: classpath*:mapper/**/*Mapper.xml
  # Loading the overall file.
  configLocation: classpath:mybatis/mybatis-config.xml

# PageHelperSeparate Page Plugins
pagehelper:
  helperDialect: mysql
  supportMethodsArguments: true
  params: count=countSql

# SwaggerConfiguration
swagger:
  # is opened.swagger
  enabled: true
  # Requests for advance.
  pathMapping: /dev-api

# PreventedXSSAttack
xss:
  # Filter to switch.
  enabled: true
  # Excluding the link.（Separate with several comics.）
  excludes: /system/notice
  # matching the link.
  urlPatterns: /system/*,/monitor/*,/tool/*
